name: Publish Package to npmjs

on:
  pull_request:
    branches:  [ main ] 
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Step 4 - Modifying repo level .npmrc file for npm registry
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_PUBLIC_TOKEN }}
        run: |
          pushd $GITHUB_WORKSPACE/$repoName
          echo "registry=https://registry.npmjs.com/" >> .npmrc
          echo "//registry.npmjs.com/:_authToken=${NPM_TOKEN}" >> .npmrc
          cp .npmrc ~/.npmrc
          popd
              
      - run: npm install -g npm
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_PUBLIC_TOKEN }}